apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-stock
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    helm.sh/chart: {{ template "sma-alert.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  stocks.yaml: |
    issuers:
{{ toYaml .Values.issuers  | indent 4 }}
