---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    helm.sh/chart: {{ template "sma-alert.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  schedule: {{ .Values.cronSchedule }}
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: {{ .Release.Name }}
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
            imagePullPolicy: Always
            env:
            - name: STOCK_LISTS_FILEPATH
              value: "/etc/sma-alert/stocks.yaml"
            envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-config
            - secretRef:
                name: {{ .Values.secret }}
            volumeMounts:
            - name: {{ .Release.Name }}-stock
              mountPath: /etc/sma-alert
          volumes:
            - name: {{ .Release.Name }}-stock
              configMap:
                name: {{ .Release.Name }}-stock
