name: Chart

on:
  create:
    tags:
      - v*

env:
  CHART_USERNAME: ${{ secrets.CHART_USERNAME }}
  CHART_PASSWORD: ${{ secrets.CHART_PASSWORD }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Deploy
      run: |
        cd charts/releases
        for FILE in *; do curl -X POST -u $CHART_USERNAME:$CHART_PASSWORD --data-binary "@$FILE" https://charts.zufardhiyaulhaq.com/api/charts && sleep 5; done
